name: Terraform Setup
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  push:
    branches: [ "master"]
jobs:
  testing:
    runs-on: ubuntu-latest    
    steps:
      - name: testing the code
        run: echo "testing the code"